
online: false

logging.config: classpath:log-test.xml

server.port: 8787

spring.application.name: web-manager

spring:
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false

register.center: http://test1:8761/eureka/,http://test2:8761/eureka/,http://test3:8761/eureka/
eureka:
  client:
    healthcheck.enabled: true
    registry-fetch-interval-seconds: 10
    serviceUrl.defaultZone: ${register.center}
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# feign.hystrix.enabled: true

#spring:
#  zipkin.base-url: http://127.0.0.1:9411
#  sleuth.sampler.percentage: 0.1
