
spring.datasource:
  url: jdbc:mysql://db-common-prod:3306/test_common_db?useAffectedRows=true&useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useLegacyDatetimeCode=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&queryInterceptors=com.github.common.sql.ShowSql8Interceptor
  username: test_common_user
  password: test_common_pass
  hikari:
    minimumIdle: 2
    maximumPoolSize: 2
    dataSourceProperties:
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      cachePrepStmts: true
      useServerPrepStmts: true

