
spring.datasource:
  url: jdbc:mysql://db-common-prod:3306/prod_common_db?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useLegacyDatetimeCode=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
  username: prod_common_user
  password: prod_common_pass
  hikari:
    minimumIdle: 10
    maximumPoolSize: 30
    dataSourceProperties:
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      cachePrepStmts: true
      useServerPrepStmts: true
