
spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/order?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useLegacyDatetimeCode=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&statementInterceptors=com.github.common.sql.ShowSqlInterceptor
  username: root
  password: root
  hikari:
    minimumIdle: 1
    maximumPoolSize: 1
