
spring.datasource:
  url: jdbc:mysql://db-order-test:3306/test_order_db?useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useLegacyDatetimeCode=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&queryInterceptors=com.github.common.sql.ShowSql8Interceptor
  username: test_order_user
  password: test_order_pass
  hikari:
    minimumIdle: 2
    maximumPoolSize: 2
    dataSourceProperties:
      prepStmtCacheSize: 50
      prepStmtCacheSqlLimit: 128
      cachePrepStmts: true
      useServerPrepStmts: false
