
spring.datasource:
  url: jdbc:mysql://db-order-prod:3306/prod_order_db?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useLegacyDatetimeCode=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
  username: prod_order_user
  password: prod_order_pass
  hikari:
    minimumIdle: 10
    maximumPoolSize: 20
    dataSourceProperties:
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      cachePrepStmts: true
      useServerPrepStmts: true
