
spring.datasource:
  url: jdbc:mysql://db-order-test:3306/test_order_db?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useLegacyDatetimeCode=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&statementInterceptors=com.github.common.sql.ShowSql8Interceptor
  username: test_order_user
  password: test_order_pass
  hikari:
    minimumIdle: 2
    maximumPoolSize: 5
    dataSourceProperties:
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      cachePrepStmts: true
      useServerPrepStmts: true
