
spring.datasource:
  url: jdbc:mysql://db-product-prod:3306/prod_product_db?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
  username: prod_product_user
  password: prod_product_pass
  hikari:
    minimumIdle: 10
    maximumPoolSize: 30
    dataSourceProperties:
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      cachePrepStmts: true
      useServerPrepStmts: true
