
spring.datasource:
  url: jdbc:mysql://db-product-prod:3306/prod_product_db?useAffectedRows=true&useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useLegacyDatetimeCode=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
  username: prod_product_user
  password: prod_product_pass
  hikari:
    minimumIdle: 5
    maximumPoolSize: 10
    dataSourceProperties:
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      cachePrepStmts: true
      useServerPrepStmts: true
