
spring.datasource:
  url: jdbc:mysql://db-user-test:3306/test_user_db?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&statementInterceptors=com.github.common.sql.ShowSqlInterceptor
  username: test_user_user
  password: test_user_pass
  hikari:
    minimumIdle: 2
    maximumPoolSize: 5
    dataSourceProperties:
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      cachePrepStmts: true
      useServerPrepStmts: true
