
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db?useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useLegacyDatetimeCode=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&queryInterceptors=com.github.common.sql.ShowSql8Interceptor
    username: root
    password: root
    hikari:
      minimumIdle: 1
      maximumPoolSize: 1
  redis:
    host: 127.0.0.1
    port: 6379
