
spring.datasource:
  url: jdbc:mysql://db-user-prod:3306/prod_user_db?useAffectedRows=true&useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useLegacyDatetimeCode=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
  username: prod_user_user
  password: prod_user_pass
  # https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
  hikari:
    minimumIdle: 10
    maximumPoolSize: 20
    dataSourceProperties:
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      cachePrepStmts: true
      useServerPrepStmts: true
