
online: false

server.port: 8071

spring.application.name: queue

spring:
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false

logging.config: classpath:log-test.xml


spring.activemq:
  broker-url: failover:(tcp://ip:port)?timeout=3000&startupMaxReconnectAttempts=5
  user: admin
  password: admin
  pool:
    enabled: true
    max-connections: 5

register.center: http://test1:8761/eureka/,http://test2:8761/eureka/,http://test3:8761/eureka/
eureka:
  client:
    healthcheck.enabled: true
    registry-fetch-interval-seconds: 10
    serviceUrl.defaultZone: ${register.center}
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

#spring:
#  zipkin.base-url: http://127.0.0.1:9411
#  sleuth.sampler.percentage: 0.1
