
online: false

logging.config: classpath:log-dev.xml

server.port: 8686

spring.application.name: web-backend

spring:
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false

register.center: http://127.0.0.1:8761/eureka/
eureka:
  client:
    # 开启健康检查(需要 spring-boot-starter-actuator 包)
    healthcheck.enabled: true
    # 客户端间隔多久去拉取服务注册信息, 默认为 30 秒
    registry-fetch-interval-seconds: 20
    serviceUrl.defaultZone: ${register.center}
  instance:
    # 客户端发送心跳给注册中心的频率, 默认 30 秒
    lease-renewal-interval-in-seconds: 20
    # 服务端在收到最后一个心跳后的等待时间. 超出将摘除该实例, 默认 90 秒, 此值至少要大于 lease-renewal-interval-in-seconds
    lease-expiration-duration-in-seconds: 60

# feign.hystrix.enabled: true

#zuul:
#  ignored-services: web-manager
#  routes:
#    common:
#      path: /common/**
#      serviceId: common
#      stripPrefix: false
#    user:
#      path: /user/**
#      serviceId: user
#      stripPrefix: false
#    product:
#      path: /product/**
#      serviceId: product
#      stripPrefix: false
#    trade:
#      path: /trade/**
#      serviceId: trade
#      stripPrefix: false

#spring:
#  zipkin.base-url: http://127.0.0.1:9411
#  sleuth.sampler.percentage: 0.1
