
online: false

logging.config: classpath:log-test.xml

server.port: 8686

spring.application.name: web-backend

spring:
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false

register.center: http://test1:8761/eureka/,http://test2:8761/eureka/,http://test3:8761/eureka/
eureka:
  client:
    healthcheck.enabled: true
    registry-fetch-interval-seconds: 10
    serviceUrl.defaultZone: ${register.center}
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# feign.hystrix.enabled: true

#zuul:
#  ignored-services: web-manager
#  routes:
#    common:
#      path: /common/**
#      serviceId: common
#      stripPrefix: false
#    user:
#      path: /user/**
#      serviceId: user
#      stripPrefix: false
#    product:
#      path: /product/**
#      serviceId: product
#      stripPrefix: false
#    trade:
#      path: /trade/**
#      serviceId: trade
#      stripPrefix: false

#spring:
#  zipkin.base-url: http://127.0.0.1:9411
#  sleuth.sampler.percentage: 0.1
