
online: false

logging.config: classpath:log-test.xml

spring.application.name: search-sync

spring.datasource:
  url: jdbc:mysql://test_search_db?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&statementInterceptors=com.github.common.sql.ShowSqlInterceptor
  username: test_search_user
  password: test_search_pass
  hikari:
    minimumIdle: 2
    maximumPoolSize: 5
    dataSourceProperties:
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      cachePrepStmts: true
      useServerPrepStmts: true

